/**
 * create-wl-payment-link — Supabase Edge Function (admin only)
 *
 * Admin calls this to create a single-use 5yr WL payment request for a specific email.
 * Returns the payment URL to share with the customer.
 *
 * Env: STRIPE_SECRET_KEY, STRIPE_PRICE_WL_5Y, APP_URL
 */

import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const STRIPE_SECRET = Deno.env.get("STRIPE_SECRET_KEY") ?? "";
const PRICE_WL_5Y   = Deno.env.get("STRIPE_PRICE_WL_5Y") ?? "";
const APP_URL        = Deno.env.get("APP_URL") ?? "http://localhost:5173";

const corsHeaders = {
  "Access-Control-Allow-Origin":  "*",
  "Access-Control-Allow-Headers": "Content-Type, Authorization, apikey, x-client-info",
};

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") return new Response(null, { status: 204, headers: corsHeaders });

  const headers = { "Content-Type": "application/json", ...corsHeaders };

  try {
    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
    );

    // Auth + admin check
    const authHeader = req.headers.get("Authorization") ?? "";
    const { data: { user }, error: authErr } = await supabase.auth.getUser(
      authHeader.replace("Bearer ", ""),
    );
    if (authErr || !user) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), { status: 401, headers });
    }
    const { data: roleRow } = await supabase
      .from("user_roles")
      .select("role")
      .eq("user_id", user.id)
      .maybeSingle();
    if (roleRow?.role !== "super_admin") {
      return new Response(JSON.stringify({ error: "Forbidden: super-admin only" }), { status: 403, headers });
    }

    const body = await req.json().catch(() => ({}));
    const email      = (body.email      as string)?.trim().toLowerCase();
    const brand_name = (body.brand_name as string)?.trim();
    const slug       = (body.slug       as string)?.trim().toLowerCase().replace(/[^a-z0-9-]/g, "-");

    if (!email || !brand_name || !slug) {
      return new Response(JSON.stringify({ error: "email, brand_name and slug are required" }), { status: 400, headers });
    }

    // Create the payment request record — token is auto-generated by DB default
    const { data: record, error: insertErr } = await supabase
      .from("wl_payment_requests")
      .insert({
        admin_id:   user.id,
        email,
        brand_name,
        slug,
        plan_id:    "wl_5_years",
        amount:     3399,
        currency:   "USD",
        status:     "pending",
      })
      .select("id, token")
      .single();

    if (insertErr || !record) {
      return new Response(JSON.stringify({ error: insertErr?.message ?? "Insert failed" }), { status: 500, headers });
    }

    const token     = record.token;
    const paymentUrl = `${APP_URL}/wl-checkout/${token}`;

    // Optionally pre-create Stripe checkout session now so the URL is ready-to-open
    // (We create it fresh on-demand in the page instead, to keep it simpler)

    return new Response(
      JSON.stringify({ payment_url: paymentUrl, token, email }),
      { status: 200, headers },
    );
  } catch (err) {
    console.error("create-wl-payment-link error:", err);
    return new Response(JSON.stringify({ error: "Internal error" }), { status: 500, headers });
  }
});
